### ISSUE TITLE
E_NOTICE for compact in PHP 7.3

### ISSUE THREAD

**Issue by kraftner** [felixarntz/plugin-lib#6]
[Since PHP 7.3.0 `compact()` issues an E_NOTICE if a variable is unset.](https://www.php.net/manual/en/function.compact.php#refsect1-function.compact-changelog)

This `compact(): Undefined variable: limits` happens here:

https://github.com/felixarntz/plugin-lib/blob/be6d44493919781f115f9f69d5ffd22af0f67d17/src/db-objects/query.php#L505

**Comment by mahype** [comment]
I have made a fork from this repository, because I need to work with the library daily. ;) I have added changes to the repository depending your issue:

https://github.com/awsmug/plugin-lib/commit/3a1ee039beb4ffe3fe54bc968b354260c5f11b95

**Comment by felixarntz** [comment]
@mahype Would be great if you could create a PR with this fix here. :)
